#!/usr/bin/env bash

PG_VERSION="18"
PG_USER="postgres"
PG_GROUP="postgres"
PG_BIN="/usr/lib/postgresql/${PG_VERSION}/bin"

BASE_DIR="/databases/postgresql18"
LISTEN_ADDRESSES="127.0.0.1"

SHARED_BUFFERS="128MB"
WORK_MEM="1MB"
MAINTENANCE_WORK_MEM="32MB"
AUTOVACUUM_WORK_MEM="16MB"
HASH_MEM_MULTIPLIER="1.0"
LOGICAL_DECODING_WORK_MEM="16MB"
MAX_CONNECTIONS="20"

PASSWORD_FILE="${BASE_DIR}/.logical_replication_password"

PASSWORD_ENCRYPTION="scram-sha-256"
MAX_WAL_SENDERS="5"

PG_ENCODING="UTF8"
PG_LOCALE="C.UTF-8"

LOGGING_COLLECTOR="on"
LOG_DIRECTORY="log"
LOG_CONNECTIONS="on"
LOG_DISCONNECTIONS="on"

SERVICE_TYPE="notify"
SERVICE_TIMEOUT_START="0"
SERVICE_TIMEOUT_STOP="120"
SERVICE_RESTART="on-failure"
SERVICE_RESTART_SEC="5"
OOM_SCORE_ADJUST="-900"
